### PR TITLE
Fix bug when a value is null

### LINKED ISSUE #121: Form goes wrong for some reason
```
{
  "origin": "toto.txt",
  "domain": null,
  "conditions": {
    "queryString": {
      "not": false,
      "val": "cat=129"
    }
  },
  "source": {
    "not": false,
    "val": "^/abc\\.aspx",
    "flags": ""
  },
  "result": {
    "code": 301,
    "destination": "/?"
  },
  "index": 145
}
```

with mapping:

```
{
  "conditions": {
    "properties": {
      "headers": {
        "type": "object",
        "enabled": false
      },
      "host": {
        "properties": {
          "flags": {
            "type": "string",
            "index": "not_analyzed"
          },
          "not": {
            "type": "boolean"
          },
          "val": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "method": {
        "properties": {
          "flags": {
            "type": "string",
            "index": "not_analyzed"
          },
          "not": {
            "type": "boolean"
          },
          "val": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "port": {
        "properties": {
          "flags": {
            "type": "string",
            "index": "not_analyzed"
          },
          "not": {
            "type": "boolean"
          },
          "val": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "queryString": {
        "properties": {
          "flags": {
            "type": "string",
            "index": "not_analyzed"
          },
          "not": {
            "type": "boolean"
          },
          "val": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "url": {
        "properties": {
          "flags": {
            "type": "string",
            "index": "not_analyzed"
          },
          "not": {
            "type": "boolean"
          },
          "val": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
    }
  },
  "count": {
    "type": "long"
  },
  "domain": {
    "type": "string",
    "index": "not_analyzed"
  },
  "index": {
    "type": "long"
  },
  "origin": {
    "type": "string",
    "index": "not_analyzed"
  },
  "result": {
    "properties": {
      "code": {
        "type": "integer"
      },
      "destination": {
        "type": "string",
        "index": "not_analyzed"
      },
      "function": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  },
  "source": {
    "properties": {
      "flags": {
        "type": "string",
        "index": "not_analyzed"
      },
      "not": {
        "type": "boolean"
      },
      "val": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  },
  "weight": {
    "type": "long"
  }
}
```

I get following error in console:
```
nhandled rejection TypeError: Cannot convert undefined or null to object
    at Array.forEach (native)
From previous event:
    at DocumentCreateOrUpdate.Vue.$emit (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9342:22)
    at DocumentCreateOrUpdate.Vue.$broadcast (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9373:41)
    at eval (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:2062:2), <anonymous>:1:25031)
    at Object.eval [as fn] (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:2062:2), <anonymous>:1:1245)
    at n (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:2062:2), <anonymous>:2:10006)
    at bound WrappedWebSocket.client.onmessage (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:2062:2), <anonymous>:2:8884)
From previous event:
    at DocumentCreateOrUpdate.Vue._callHook (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8235:21)
    at DocumentCreateOrUpdate.ready (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9464:10)
    at DocumentCreateOrUpdate.on (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9261:10)
    at DocumentCreateOrUpdate.Vue.$emit (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9342:22)
    at DocumentCreateOrUpdate.Vue._callHook (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8238:10)
    at callAttach (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8197:13)
    at Array.forEach (native)
    at DataLayout.onAttached (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8185:22)
    at DataLayout.Vue.$emit (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9342:22)
    at DataLayout.Vue._callHook (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8238:10)
    at callAttach (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8197:13)
    at Array.forEach (native)
    at Home.onAttached (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8185:22)
    at Home.Vue.$emit (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9342:22)
    at Home.Vue._callHook (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:8238:10)
    at insert (eval at <anonymous> (http://ec2-54-70-77-155.us-west-2.compute.amazonaws.com:3000/app.js:644:2), <anonymous>:9178:10)
```

### PR DESCRIPTION
**Pull request by jenow**
Fix #121

### CODE REVIEW

File: src/services/documentFormat.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export const getUpdatedSchema = (jsonDocument, collection) => {
   let properties = {}
   let schema = {}
 
-  if (type === 'object' || type === 'nested') {
+  if ((type === 'object' && jsonDocument != null) || type === 'nested') {
```
Comment (scottinet) [inline src/services/documentFormat.js]: Can `jsonDocument` be undefined?

Comment (jenow) [inline src/services/documentFormat.js]: It can't be, it comes from elasticsearch, if it is undefined the attribute won't even be there

Comment (scottinet) [inline src/services/documentFormat.js]: Great. :smile:
